name: GitHub Action Node JS

on:
  pull_request:
    branches: [ master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v2
        with:
          node-version: 12
      - run : npm ci
      - run : npm test
      - run : npm run build
          